libwbxml/libwbxml

test/api/CMakeLists.txt
Use the ldflags provided by pkg-config if pkg-config is available. Without this it fails to build on my Ubuntu 14.04 machine with the following error because -pthread is missing:
```
Linking C executable test_wbxml_base64
cd /home/jeroen/github/libwbxml/build/test/api && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_wbxml_base64.dir/link.txt --verbose=1
/usr/bin/cc      CMakeFiles/test_wbxml_base64.dir/test_wbxml_base64.o CMakeFiles/test_wbxml_base64.dir/api_test.o  -o test_wbxml_base64 -rdynamic ../../src/libwbxml2.so.1.0.5 -lcheck_pic -lrt -lm -lexpat -Wl,-rpath,/home/jeroen/github/libwbxml/build/src 
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libcheck_pic.a(check_pack.o): undefined reference to symbol '__pthread_unregister_cancel@@GLIBC_2.3.3' …
```
=> Use CHECK_LDFLAGS if pkg-config is available

INSTALL
CMake will support to build static library.
Added option to build either static, shared or both libraries.
Can be controlled using standard CMake flags : BUILD_SHARED_LIBS & BUILD_STATIC_LIBS.
=> CMake support for static library.

src/wbxml_encoder.c
Before returning with error : WBXML_ERROR_INTERNAL , "referenced" must be freed. Otherwise it will leak memory.
=> Possible Resource leak.

src/wbxml_encoder.c
When i=0, list is NULL. But subsequently as the loop iterates, "list" is allocated memory. Hence it need to be free before return at line:3766.
wbxml_list_destroy already checks if list is NULL, so no need to check for NULL before destroying "list" at this place.
=> Fix memory leak in "list"

src/wbxml_parser.c
Avoid typecasting in malloc.
C compiler automatically typecasts.
Please review, I then I will submit patches for other files also.
=> malloc typecasting is unnecessary in C

src/wbxml_buffers.c
C Compiler does automatic typecasting.
=> Avoid malloc typecast in wbxml_buffers.c

src/wbxml_base64.c
C Compiler does auto typecasting.
=> Avoid malloc typecast in wbxml_base64.c

src/wbxml_charset.c
C Compiler can do auto typecasting.
=> Avoid malloc typecast in wbxml_charset.c

src/wbxml_elt.c
C Compiler can do auto typecasting.
=> Avoid malloc typecast in wbxml_elt.c

src/wbxml_lists.c
C Compiler can do automatic typecasting.
=> Avoid typecasting for malloc in wbxml_lists.c

src/wbxml_tree.c
C Compiler can do typecasting automatically.
=> Avoid malloc typecast in wbxml_tree.c

src/wbxml_parser.c
1585 : ext = wbxml_malloc(WBXML_STRLEN(var_begin) +
ext malloced at line 1585 should be freed when default case is executed in line 1628.
=> Memory leak of ext when default case is executed.

src/wbxml_buffers.c, src/wbxml_buffers.h, test/api/test_wbxml_base64.c, test/api/test_wbxml_buffers.c, test/api/test_wbxml_errors.c
Fixed MacOS X compiler warnings of Travis CI. This includes two fixes of the internal buffer API.
=> Fixed MacOS X compiler warnings of Travis CI.

src/wbxml_encoder.c
This can happen when an unknown tag was encountered in wbxml_tag_get_xml_name.
=> Fix crash where node or node->name are NULL

ChangeLog, src/wbxml_tables.c
ActiveSync => Code page: 0x11 AirSyncBase => Content => WBXML_BINARY_OPTION
=> Added fix from issue #58 to correct encoding of Microsoft ActiveSync.

test/tools/launchTests.sh
When enabling Asan (address sanitizer) feature in gcc, the libasan library is not getting loaded due to fixed LD_LIBRARY_PATH.
Modify to take external lib loading path also to maintain generic behaviour.
=> Fix outside library loading

tools/wbxml2xml_tool.c, tools/xml2wbxml_tool.c
Below errors are reported.
==12503==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 16 byte(s) in 1 object(s) allocated from:
#0 0x7f1353996a18 in __interceptor_malloc ../../.././libsanitizer/asan/asan_malloc_linux.cc:38
#1 0x7f1353678151 in wbxml_malloc My_DIR/libwbxml-master/src/wbxml_mem.c:48
#2 0x7f1353665f72 in wbxml_conv_wbxml2xml_create My_DIR/libwbxml-master/src/wbxml_conv.c:71
#3 0x402a24 in main My_DIR/libwbxml-master/tools/wbxml2xml_tool.c:326
#4 0x7f1353059f44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
==6407==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 8 byte(s) in 1 object(s) allocated from:
#0 0x7fbbac2b3a18 in __interceptor_malloc ../../.././libsanitizer/asan/asan_malloc_linux.cc:38
#1 0x7fbbabf95151 in wbxml_malloc …
=> Fix leak-sanitizer issues in tools

test/api/test_wbxml_base64.c
Patch for below issue detected by leak-sanitizer:
./test_wbxml_base64
Running suite(s): name
=================================================================
==26991==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 1 byte(s) in 1 object(s) allocated from:
#0 0x7f97d0b92a18 in __interceptor_malloc ../../.././libsanitizer/asan/asan_malloc_linux.cc:38
#1 0x7f97d0874151 in wbxml_malloc My_DIR/libwbxml-master/src/wbxml_mem.c:48
#2 0x7f97d085ce76 in wbxml_base64_decode My_DIR/libwbxml-master/src/wbxml_base64.c:137
#3 0x40329a in test_decode My_DIR/libwbxml-master/test/api/test_wbxml_base64.c:36
#4 0x405f36 in srunner_run (My_DIR/libwbxml-master/build/test/api/test_wbxml_base64+0x405f36)
Direct leak of 1 byte(s) in 1 object(s) allocated from:
#0 0x7f97d0b92a18 in __interceptor_malloc …
=> Fix memory leak detected by leak-sanitizer

src/wbxml_tree.h
This minor change ensures the internal header file is used rather than the system installed header file.
=> Use internal local header rather than installed header.

CMakeLists.txt, ChangeLog, INSTALL, THANKS, src/CMakeLists.txt
Back in January 2011 the API [was reduced](https://github.com/libwbxml/libwbxml/commit/4add46f7a27efd326dfbaddd11bf3aec86602642) to expose (as I understand it) only the XML<-->WBXML conversion functions.
We have a number of projects that make more direct use of the API (for example [see here](https://git.sailfishos.org/mer-core/provisioning-service/blob/master/src/provisioning-decoder.c)), and in the process of updating them to the latest version (please don't ask why it's taken over 8 years to do this) I stumbled on this change.
In order to get these projects to build without access to the (now internal) header files, significant changes to them would be required. In fact I'm unclear on how this is supposed to be achieved with just the API now visible, but it looks like it would require …
=> Provide option to install internal header files

ChangeLog, THANKS, src/wbxml_internals.h, src/wbxml_parser.c, src/wbxml_tree_clb_xml.c
Three parts are addressed:
1. Crash in case of damaged wbxml file.
2. Hard-coded colon as a namespace separator in SyncML related code.
3. Change the default namespace separator.
See previous comments on issue #76.
=> Change namespace separator

ChangeLog, README, RELEASE
=> Changed location of releases to GitHub in README and minor SVN cleanup.

RELEASE
Removed the building of packages which was necessary for SourceForge's file release system.
=> Removed the building of packages

ChangeLog, test/tools/launchTests.sh
When I introduced an error into test/tools/normalize_xml.pl, the
launchTests.sh kept reporting success:
~~~~
$ ./launchTests.sh /tmp/libwbxml/test/tools activesync 1
Test suite directory is /tmp/libwbxml/test/tools
----------------------------
Entering into: activesync
----------------------------
. activesync-001-settings_device_information.xml
Converting into: /tmp/LibWBXMLTestSuite.iS8/activesync/activesync-001-settings_device_information.wbxml
xml2wbxml succeeded
Converting back: /tmp/LibWBXMLTestSuite.iS8/activesync/activesync-001-settings_device_information.xml
wbxml2xml succeeded
Comparing the original and the generated XML ... Can't locate XXX/English.pm in @INC (you may need to install the XXX::English module) (@INC contains: /usr/local/lib64/perl5/5.34 …
=> tests: Check for normalize_xml.pl failure

src/wbxml_buffers.c, src/wbxml_parser.c, src/wbxml_tree.c, test/api/test_wbxml_encoder_internals.c
Building with -Wall compiler option, GCC reports a few unused variables. This patch fixes the warnings.
A notable case was in decode_wv_datetime() where a memory allocation failure was ignored.
=> Remove unused variables

ChangeLog, src/wbxml_internals.h
Removed pragma 4061 from wbxml_internals.h which caused compiler errors on win32 platform (issue #75).
=> Removed pragma 4061 from wbxml_internals.h

cmake/CMakeLists.txt
libwbxml2-config.cmake was installed into /cmake/libwbxml2 directory because CMAKE_INSTALL_LIBDIR was not set:
/usr/bin/cmake --install redhat-linux-build
-- Install configuration: ""
-- Installing: /home/test/fedora/libwbxml/libwbxml-0.11.10-build/BUILDROOT/usr/lib64/pkgconfig/libwbxml
[...]
-- Installing: /home/test/fedora/libwbxml/libwbxml-0.11.10-build/BUILDROOT/cmake/libwbxml2/libwbxml2-config.cmake
-- Installing: /home/test/fedora/libwbxml/libwbxml-0.11.10-build/BUILDROOT/cmake/libwbxml2/libwbxml2-config-version.cmake
The root cause was that CMAKE_INSTALL_LIBDIR is defined by GNUInstallDirs module which was not included.
This patch fixes it.
=> Fix installing CMake configuration files

CMakeLists.txt
Expat added CMake scripts in 2.3.0 version. Configuring libwbxml with older Expat failed:
~~~~
CMake Error at CMakeLists.txt:97 (FIND_PACKAGE):
By not providing "FindExpat.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Expat", but
CMake did not find one.
Could not find a package configuration file provided by "Expat" with any of
the following names:
ExpatConfig.cmake
expat-config.cmake
Add the installation prefix of "Expat" to CMAKE_PREFIX_PATH or set
"Expat_DIR" to a directory containing one of the above files.  If "Expat"
provides a separate development package or SDK, be sure it has been
installed.
~~~~
The cause was that FIND_PACKAGE() was incorrectly called with REQUIRED option. This patch fixes it.
=> Fix a pkg-config fallback from CMake scripts when detecting Expat
